### ISSUE TITLE
Runtime panic when attempting to run pdfbooklet on input

### ISSUE THREAD

**Issue by lawrencetungsten** [dbaynard/booklet#2]
Hi,
I encounter this issue after installing and running the program. please advice.

```
thread 'main' panicked at 'attempted to leave type `linked_hash_map::Node<std::vec::Vec<u8>, object::Object>` uninitialized, which is invalid', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/linked-hash-map-0.3.0/src/lib.rs:203:52
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by dbaynard** [comment]
Hello,

I can reproduce this issue. I’m not doing any maintenance work on this project at the moment, so I can’t offer a fix. I’ll come back to this at some point, but I have no immediate plans to do so.

That said, it would be helpful if you include details in your issue message, beyond what you’ve written.

1. Which version of the tool are you using?
2. Which platform are you using? I’m guessing linux, based on the path in the error message. But I don’t know which linux distribution, and which architecture.
3. How did you install it? From source, or with the release binary? If from source, which versions of the rust toolchain did you use?
4. What actually caused the issue? If I run `pdfbooklet --help` I don’t see an issue, but when I try to run `pdfbooklet` on input then I can reproduce (on macos).

In addition, I’ve edited your comment to use backticks to quote the error message, and added an informative title.

**Comment by dbaynard** [comment]
It might relate to https://github.com/contain-rs/linked-hash-map/pull/100 — I’ve just encountered an equivalent error in a completely different tool.
